# Generated by Django 5.2.7 on 2025-10-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.userregistration'),
        ),
    ]
