# Generated by Django 5.2.7 on 2025-11-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userregistration_assigned_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='main_app.userregistration'),
        ),
    ]
