# Generated by Django 5.2.7 on 2025-11-02 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_userregistration_assigned_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
