# Generated by Django 5.2.7 on 2025-11-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userregistration_reviewed_at_userregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to='main_app.userregistration'),
        ),
    ]
