# Generated by Django 5.2.7 on 2025-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_projectsubmission_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
