# Generated by Django 5.2.7 on 2025-11-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_projectsubmission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to='main_app.userregistration'),
        ),
    ]
