# Generated by Django 5.2.7 on 2025-11-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_submissiondeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondeadline',
            name='teacher_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
