# Generated by Django 5.2.7 on 2025-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_submissiondeadline_teacher_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
