# Generated by Django 5.2.7 on 2025-11-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_userregistration_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
