# Generated by Django 5.2.8 on 2025-11-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_userregistration_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='admin_code',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='teacher_id',
        ),
    ]
